name: Backend Deploy

on:
  push: 
    branches:
    - main
    paths:
    - 'leapcode-core/**'

jobs:
  build:
    name: Backend Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    # deploy to firebase