name: Frontend Deploy

on:
  push: 
    branches:
    - main
    paths:
    - 'leapcode-next/**'

jobs:
  build:
    name: Frontend Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    # deploy to vercel
